postgres:
  container_name: kotlin_example_app_mongo
  environment:
    MONGO_INITDB_ROOT_USERNAME: root
    MONGO_INITDB_ROOT_PASSWORD: example
  image: mongo
  ports:
    - 27017:27017
redis:
  container_name: kotlin_example_app_redis
  image: redis
  command: redis-server --requirepass password
  ports:
    - 6379:6379
kafka:
  container_name: kotlin_example_kafka
  image: spotify/kafka
  environment:
    ADVERTISED_HOST: localhost
    ADVERTISED_PORT: 9092
  ports:
    - 2181:2181
    - 9092:9092