version: 2.1

parameters:
  grpc-lib-modified:
    type: boolean
    default: false
  version_tag:
    type: string
    default: latest

jobs:
  build:
    parameters:
      app_name:
        type: string

    machine:
      resource_class: medium
      image: ubuntu-2004:202010-01

    working_directory: ~/<< parameters.app_name >>

    steps:
      - checkout
      - run:
          name: Build Grpc Lib
          command: |
            echo Build << parameters.app_name >> Grpc Lib
      - run:
          name: Publish to Artifactory
          command: |
            echo Publish << parameters.app_name >>:${CIRCLE_SHA1} to Artifactory

  done:
    machine:
      resource_class: medium
      image: ubuntu-2004:202010-01

    steps:
      - checkout
      - run:
          name: echo done message
          command: |
            echo Done!!!

workflows:
  version: 2

  grpc_lib:
    when: << pipeline.parameters.grpc-lib-modified >>
    jobs:
      - build:
          name: Build grpc_lib
          app_name: grpc_lib

  nothing_to_run:
    when:
      and:
        - not: << pipeline.parameters.grpc-lib-modified >>
    jobs:
      - done:
          name: Nothing to run
