version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.1.0
  docker: circleci/docker@1.5.0

parameters:
  grpc-lib-modified:
    type: boolean
    default: false
  mongo-service-modified:
    type: boolean
    default: false
  rdbms-service-modified:
    type: boolean
    default: false

jobs:
  build:
    parameters:
      app_name:
        type: string

    machine:
      resource_class: medium
      image: ubuntu-2004:202010-01

    working_directory: ~/<< parameters.app_name >>

    steps:
      - checkout
      - run:
          name: echo build message
          command: |
            echo build << parameters.app_name >>

  deploy:
    parameters:
      app_name:
        type: string

    machine:
      resource_class: medium
      image: ubuntu-2004:202010-01

    working_directory: ~/<< parameters.app_name >>

    steps:
      - checkout
      - run:
          name: echo build message
          command: |
            echo deploy << parameters.app_name >>

  done:
    machine:
      resource_class: medium
      image: ubuntu-2004:202010-01

    steps:
      - checkout
      - run:
          name: echo done message
          command: |
            echo Done!!!

workflows:
  version: 2

  grpc_lib:
    when: << pipeline.parameters.grpc-lib-modified >>
    jobs:
      - build:
          name: Build grpc_lib
          app_name: grpc_lib
      - deploy:
          name: Deploy grpc_lib
          app_name: grpc_lib

  mongo_service:
    when: << pipeline.parameters.mongo-service-modified >>
    jobs:
      - build:
          name: Build mongo_service
          app_name: mongo_service
      - deploy:
          name: Deploy mongo_service
          app_name: mongo_service

  rdbms_service:
    when: << pipeline.parameters.rdbms-service-modified >>
    jobs:
      - build:
          name: Build rdbms_service
          app_name: rdbms_service
      - deploy:
          name: Deploy rdbms_service
          app_name: rdbms_service

  nothing_to_run:
    when:
      or:
        - not: << pipeline.parameters.grpc-lib-modified >>
        - not: << pipeline.parameters.mongo-service-modified >>
        - not: << pipeline.parameters.rdbms-service-modified >>
    jobs:
      - done:
          name: Nothing to run
