version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.1.0
  docker: circleci/docker@1.7.0

parameters:
  grpc-lib-modified:
    type: boolean
    default: false
  mongo-service-modified:
    type: boolean
    default: false
  rdbms-service-modified:
    type: boolean
    default: false
  version_tag:
    type: string
    default: latest

commands:
  aws-login:
    steps:
      - run:
          name: Login in to AWS
          command: echo Login to AWS

  envsubst-action:
    steps:
      - run:
          name: Environment Variable Subsitution
          command: |
            envsubst < "${INPUT_FILE}" > tmp
            mv tmp "${OUTPUT_FILE}"
            cat "${OUTPUT_FILE}"

jobs:
  build:
    machine:
      resource_class: medium
      image: ubuntu-2004:202010-01

    working_directory: ~/build/<< parameters.app_name >>

    parameters:
      app_name:
        type: string

    steps:
      - checkout:
          path: ~/build
      - run:
          name: Setup common environment variables
          command: |
            echo 'export APP_NAME="<< parameters.app_name >>"' >> $BASH_ENV
            if [ "<< parameters.app_name >>" == "mongo_service" ]
            then
              echo 'export INPUT_FILE="mongo_test.txt"' >> $BASH_ENV
              echo 'export OUTPUT_FILE="mongo_test.txt"' >> $BASH_ENV
            elif [ "<< parameters.app_name >>" == "rdbms_service" ]
            then
              echo 'export INPUT_FILE="rdbms_test.txt"' >> $BASH_ENV
              echo 'export OUTPUT_FILE="rdbms_test.txt"' >> $BASH_ENV
            fi
      - envsubst-action
      - run:
          name: Hash dependency info
          command: |
            mkdir -p build
            md5sum gradle/wrapper/gradle-wrapper.properties settings.gradle.kts build.gradle.kts > build/deps.md5
      - restore_cache:
          key: gradle-{{ checksum "build/deps.md5" }}
      - run:
          name: Gradlew Build
          command: |
            chmod +x gradlew
            ./gradlew build -x test
      - save_cache:
          key: gradle-{{ checksum "build/deps.md5" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
      - docker/build:
          image: ${DOCKER_LOGIN}/<< parameters.app_name >>
          tag: $CIRCLE_SHA1,<< pipeline.parameters.version_tag >>
      - docker/check
      - docker/push:
          image: ${DOCKER_LOGIN}/<< parameters.app_name >>
          tag: $CIRCLE_SHA1,<< pipeline.parameters.version_tag >>

  deploy:
    docker:
      - image: cimg/base:2021.04
    resource_class: medium

    working_directory: ~/deploy/<< parameters.app_name >>

    parameters:
      app_name:
        type: string

    steps:
      - checkout:
          path: ~/deploy
      - aws-login
      - run:
          name: Deploy Docker Image to EKS
          command: |
            echo Deploy << parameters.app_name >>:<< pipeline.parameters.version_tag >> to EKS

  all_filtered_job:
    docker:
      - image: cimg/base:2021.04
    resource_class: small

    steps:
      - run:
          name: echo done message
          command: |
            echo All Workflows have been filtered from this Pipeline.No Jobs have been run.

workflows:
  version: 2

  # grpc_lib:
  #   when: << pipeline.parameters.grpc-lib-modified >>
  #   jobs:
  #     - build:
  #         name: Build grpc_lib
  #         app_name: grpc_lib
  #     - deploy:
  #         name: Deploy grpc_lib
  #         requires:
  #           - Build grpc_lib
  #         app_name: grpc_lib

  mongo_service:
    when: << pipeline.parameters.mongo-service-modified >>
    jobs:
      - build:
          app_name: mongo_service
      - deploy:
          requires:
            - build
          app_name: mongo_service

  rdbms_service:
    when: << pipeline.parameters.rdbms-service-modified >>
    jobs:
      - build:
          app_name: rdbms_service
      - deploy:
          requires:
            - build
          app_name: rdbms_service

  all_filtered:
    when:
      and:
        - not: << pipeline.parameters.grpc-lib-modified >>
        - not: << pipeline.parameters.mongo-service-modified >>
        - not: << pipeline.parameters.rdbms-service-modified >>
    jobs:
      - all_filtered_job:
          name: All filtered Job
