version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.1.0
  docker: circleci/docker@1.7.0

parameters:
  grpc-lib-modified:
    type: boolean
    default: false
  mongo-service-modified:
    type: boolean
    default: false
  rdbms-service-modified:
    type: boolean
    default: false
  version_tag:
    type: string
    default: latest

commands:
  aws-login:
    steps:
      - run:
          name: Login in to AWS
          command: echo Login to AWS

jobs:
  build:
    parameters:
      app_name:
        type: string

    machine:
      resource_class: medium
      image: ubuntu-2004:202010-01

    working_directory: ~/build/<< parameters.app_name >>

    steps:
      - checkout:
          path: ~/build
      - run:
          name: Make gradlew executable
          command: |
            chmod +x gradlew
      - run: 
          name: Gradlew Clean Build
          command: |
            ./gradlew clean build -x test
      - docker/build:
          image: ${DOCKER_LOGIN}/<< parameters.app_name >>
          tag: $CIRCLE_SHA1,<< pipeline.parameters.version_tag >>
      - docker/check
      - docker/push:
          image: ${DOCKER_LOGIN}/<< parameters.app_name >>
          tag: $CIRCLE_SHA1,<< pipeline.parameters.version_tag >>

  deploy:
    parameters:
      app_name:
        type: string

    docker:
      - image: cimg/base:2021.04
    resource_class: medium

    working_directory: ~/deploy/<< parameters.app_name >>

    steps:
      - checkout:
          path: ~/deploy
      - aws-login
      - run:
          name: Deploy Docker Image to EKS
          command: |
            echo Deploy << parameters.app_name >>:<< pipeline.parameters.version_tag >> to EKS

  all_filtered_job:
    docker:
      - image: cimg/base:2021.04
    resource_class: small
      
    steps:
      - run:
          name: echo done message
          command: |
            echo All Workflows have been filtered from this Pipeline.No Jobs have been run.

workflows:
  version: 2

  # grpc_lib:
  #   when: << pipeline.parameters.grpc-lib-modified >>
  #   jobs:
  #     - build:
  #         name: Build grpc_lib
  #         app_name: grpc_lib
  #     - deploy:
  #         name: Deploy grpc_lib
  #         requires:
  #           - Build grpc_lib
  #         app_name: grpc_lib

  mongo_service:
    when: << pipeline.parameters.mongo-service-modified >>
    jobs:
      - build:
          name: Build mongo_service
          app_name: mongo_service
      - deploy:
          name: Deploy mongo_service
          requires:
            - Build mongo_service
          app_name: mongo_service

  rdbms_service:
    when: << pipeline.parameters.rdbms-service-modified >>
    jobs:
      - build:
          name: Build rdbms_service
          app_name: rdbms_service
      # - docker/publish:
      #     requires:
      #       - Build rdbms_service
      #     name: Publish rdbms_service docker image
      #     dockerfile: rdbms_service/Dockerfile
      #     image: ${DOCKER_LOGIN}/rdbms_service
      #     tag: $CIRCLE_SHA1,<< pipeline.parameters.version_tag >>
      - deploy:
          name: Deploy rdbms_service
          requires:
            - Build rdbms_service
          app_name: rdbms_service

  all_filtered:
    when:
      and:
        - not: << pipeline.parameters.grpc-lib-modified >>
        - not: << pipeline.parameters.mongo-service-modified >>
        - not: << pipeline.parameters.rdbms-service-modified >>
    jobs:
      - all_filtered_job:
          name: All filtered Job
