postgres:
  container_name: kotlin_example_app_postgres
  environment:
    - POSTGRES_PASSWORD=password
  image: postgres
  ports:
    - 5432:5432
redis:
  container_name: kotlin_example_app_redis
  image: redis
  command: redis-server --requirepass password
  ports:
    - 6379:6379