postgres:
  container_name: kotlin_example_app_postgres
  environment:
    - POSTGRES_PASSWORD=password
  image: postgres
  ports:
    - 5432:5432
redis:
  container_name: kotlin_example_app_redis
  image: redis
  command: redis-server --requirepass password
  ports:
    - 6379:6379
kafka:
  container_name: kotlin_example_kafka
  image: spotify/kafka
  environment:
    ADVERTISED_HOST: localhost
    ADVERTISED_PORT: 9092
  ports:
    - 2181:2181
    - 9092:9092